const AUTH_REQUEST = 'AUTH_REQUEST';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAILED = 'AUTH_FAILED';
const DEAUTH_REQUEST = 'DEAUTH_REQUEST';
const ERASE_ERRORS = 'ERASE_ERRORS';

export {
  AUTH_REQUEST, AUTH_SUCCESS, AUTH_FAILED, DEAUTH_REQUEST, ERASE_ERRORS,
};
